name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and package with Maven
        run: mvn clean package

      - name: Deploy to AWS CodeDeploy
        uses: sourcetoad/aws-codedeploy-action@v1
        with:
          appspec: appspec.yml
          codedeploy-application: TinyBlogCodeDeploy
          codedeploy-deployment-group: TinyBlogDeployGroup
          codedeploy-region: us-east-1
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
